### ISSUE TITLE
Copy dist to run outside the project

### ISSUE THREAD

**Issue by medz** [prisma/repro-nexus-prisma-109#1]

**Comment by medz** [comment]
@jasonkuhrt Hi，Build The docker：

```
docker build . -t example:test
```

Run the docker image, result:

```
/app/index.js:134198

        throw ono_1.default(error, dindist_1.default `

        ^


Error: Failed to get Prisma Client DMMF. An error occured while trying to import it from @prisma/client. 

Cannot find module '@prisma/client'

Require stack:

- /app/index.js

    at getPrismaClientDmmf (/app/index.js:134198:28)

    at Object.89157 (/app/index.js:134621:14)

    at __nccwpck_require__ (/app/index.js:156283:43)

    at Object.94197 (/app/index.js:134317:22)

    at __nccwpck_require__ (/app/index.js:156283:43)

    at /app/index.js:156362:70

    at /app/index.js:156402:3

    at Object.<anonymous> (/app/index.js:156405:12)


Error: Cannot find module '@prisma/client'

Require stack:

- /app/index.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)

    at Function.Module._load (internal/modules/cjs/loader.js:745:27)

    at Module.require (internal/modules/cjs/loader.js:961:19)

    at require (internal/modules/cjs/helpers.js:92:18)

    at getPrismaClientDmmf (/app/index.js:134194:21)

    at Object.89157 (/app/index.js:134621:14)

    at __nccwpck_require__ (/app/index.js:156283:43)

    at Object.94197 (/app/index.js:134317:22)

    at __nccwpck_require__ (/app/index.js:156283:43)

    at /app/index.js:156362:70 {

  code: 'MODULE_NOT_FOUND',

  requireStack: [ '/app/index.js' ],

  toJSON: [Function: toJSON],

  [Symbol(nodejs.util.inspect.custom)]: [Function: inspect]

}
```

Or copy `dist` to run outside the project, (Eg: desktop dir), run:

```
# PWD = ~/Desktop
node dist/index.js
```

**Comment by jasonkuhrt** [comment]
I've updated the scripts to force this error, no docker needed so far.
